version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'qwerty123'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - /home/nikita/Documents/docker/mysql-test/src/script/:/var/opt/
volumes:
  my-db:
